
name: Publish docs
on:
  push:
    branches:
      - test-website-doc
permissions:
  contents: write
jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Build docs
        run: make copy_docs
      - uses: actions/setup-python@v4
        with:
          python-version: 3.x
      - uses: actions/cache@v2
        with:
          key: ${{ github.ref }}
          path: .cache
      - name: Install dependencies
        run: pip install mkdocs==1.4.2 mkdocs-material==9.1.5 mdx-truly-sane-lists==1.3 mkdocs-awesome-pages-plugin==2.8.0 mkdocs_gen_files==0.5.0 GitPython==3.1.35 pytest==7.4.2
      - name: Install pyspec requirements (in testing)
        run: |
          make preinstallation
          python3 pip install ruamel.yaml==0.17.21 marko==1.0.2
          python3 pip install -r scripts/requirements.txt
      - name: Build test generation docs
        run: python3 scripts/gen_test_case_reference.py
      - run: mkdocs gh-deploy --force
